// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI.DbContexts;

#nullable disable

namespace ProductAPI.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20230118135629_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("ProductAPI.Entities.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A small kitchen knife used to gut fish",
                            Name = "Small Kitchen Knife",
                            Price = 15.60m
                        },
                        new
                        {
                            Id = 2,
                            Description = "A large kitchen knife used to cut meat",
                            Name = "Large Kitchen Knife",
                            Price = 25.29m
                        },
                        new
                        {
                            Id = 3,
                            Description = "A serving tray used to serve cheese",
                            Name = "Cheese serving tray",
                            Price = 13.90m
                        },
                        new
                        {
                            Id = 4,
                            Description = "A pressure cooker that cuts your cooking time in half",
                            Name = "Pressure cooker",
                            Price = 75.43m
                        },
                        new
                        {
                            Id = 5,
                            Description = "A cast iron pan used for cooking steak and fish",
                            Name = "Cast-Iron pan",
                            Price = 45.10m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
